import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/app/globals.css";
import Header from "@/app/components/Header/Header";
import { Toaster } from "sonner";
import CartSlider from "./components/CartSlider/CartSlider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
  title: "MY-STORE",
  description: "Generated by MY-STORE",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Header />
        <main className="pt-24 flex-1">{children}</main>
        <Footer />
        <Toaster />
        <CartSlider />
      </body>
    </html>
  );
}
